### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by xyf007** [Project-LemonLime/Project_LemonLime#141]
系统版本：Ubuntu20.04
安装过程的时候出现依赖问题，我使用 `sudo apt install -f` 来处理。
在「显示应用程序」内点击无反应，命令行运行会得到 `lemon: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version ``Qt_5.15' not found (required by lemon)`。
我觉得是我的问题但是我不知道怎么解决。

**Comment by xyf007** [comment]
百度/谷歌的结果是 `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH` 但是无果。

**Comment by CoelacanthusHex** [comment]
因为你使用 `-f` 来处理就不是正确的方法，`-f` 会无视依赖进行安装，我们的 deb 包依赖 Qt 5.15，你的系统里没有这个版本的 Qt 自然会报错。
这里提供两种解决方案：
1. 寻找提供 Qt 5.15 的 PPA 安装 Qt 5.15
2. 安装我们提供的 flatpak 包（https://github.com/Project-LemonLime/flatpak ），自动生成的包位于 https://github.com/Project-LemonLime/flatpak/actions/runs/1404829962
@alphagocc 你所打的 flatpak 包似乎未提交到 flathub （https://github.com/flathub/flathub/wiki ）

**Comment by xyf007** [comment]
那么我需要卸载原来的 Qt 吗？

**Comment by CoelacanthusHex** [comment]
如果需要卸载，那么你安装的时候应该会有提示，给出一个方案（不过咱不确定 apt 脑子有没有这么聪明，zypper 和 dnf 都能自动给出解决方案

**Comment by xyf007** [comment]
我试看看

**Comment by xyf007** [comment]
需要 11GB 空间。。我放弃了

**Comment by CoelacanthusHex** [comment]
啊，你指的哪个？只装qt应该不至于要11GiB啊

**Comment by xyf007** [comment]
Qt 在线安装包里面的 Qt 5.15.2

**Comment by CoelacanthusHex** [comment]
啊这，那个是完整的 Qt 啊，但是 LemonLime 应该只需要 qtbase，最多加个 qtnetwork

**Comment by xyf007** [comment]
Desktop gcc 64-bit 够了吗（

**Comment by alphagocc** [comment]
https://github.com/Project-LemonLime/Project_LemonLime/releases/tag/0.3.1
Fixed
