### ISSUE TITLE
[BUG] ubuntu 20.04 mle 汇报成 re

### ISSUE THREAD

**Issue by asd-a** [Project-LemonLime/Project_LemonLime#142]
**Describe the bug**
如果开了一个超过题目内存限制的数组，会报Runtime Error
以及 `assert(0)` 会报 mle 

**To Reproduce**
**如何复现**
内存限制 4 mb
代码中添加
`int a[1048576*8];`
评测结果会是RE
期望得到MLE

**Comment by alphagocc** [comment]
> `int a[1048576*8];`
评测结果会是RE
期望得到MLE

这段代码发生了段错误（`SIGSEGV`），被Linux直接终止了，无法获得究竟是什么原因导致段错误

> 以及 assert(0) 会报 mle

类似`vector`,`new`,这类在堆上分配内存的代码，无法继续分配时会抛出异常获得`SIGABRT`
而不巧，`assert(0)`也会产生`SIGABRT`

无法解决此类问题
