### ISSUE TITLE
[BUG] 用户手册描述有误

### ISSUE THREAD

**Issue by AntaresQAQ** [Project-LemonLime/Project_LemonLime#144]
文档中，在“6.2 自定义校验器(SPJ)说明”

有以下描述：

> 评测软件会向校验器传入六个参数，按照顺序分别表示标准输入文件、选手输出文件、**标准输入文件**、本测试点满分、分数输出文件、额外信息文件。

应当修正为：

> 评测软件会向校验器传入六个参数，按照顺序分别表示标准输入文件、选手输出文件、**标准输出文件**、本测试点满分、分数输出文件、额外信息文件。

<https://github.com/Project-LemonLime/Project_LemonLime/blob/master/manual/llmanual.pdf>

![image](https://user-images.githubusercontent.com/37372723/140949147-ea973a7a-6a02-4e8b-99b0-0a63274f773d.png)

**Comment by alphagocc** [comment]
我以为iotang顺手重编译了

**Comment by CoelacanthusHex** [comment]
@alphagocc 草

**Comment by AntaresQAQ** [comment]
草

**Comment by alphagocc** [comment]
Fixed
