### ISSUE TITLE
[BUG] Python 语言无法评测

### ISSUE THREAD

**Issue by hemulab** [Project-LemonLime/Project_LemonLime#147]
请问有人成功实现Python测评吗？我按照默认的设置下来，一真不能成功。

**Comment by alphagocc** [comment]
无法复现

**Comment by hemulab** [comment]
> 无法复现
或者是个人设置的问题，不知道能不能提供Project_LemonLime相应的使用教程，网上找了只有C++语言评测的教程，没有找到JAVA和Python等语言的评测教程。

**Comment by hemulab** [comment]
我尝试按照教程，建立了如下目录结构，测试 A+B.py 程序 ：
├── data
│   ├── AplusB.py
│   ├──  AplusB
│   │        ├── AplusB10.in
│   │        ├── AplusB10.out
其中，
AplusB.py 代码如下：
```python
a=input().split(' ')
print(int(a[0])+int(a[1]))
```
AplusB10.in 内容如下：
`2 3 `
AplusB10.out 内容如下：
`5`
然后在 source 目录下测评上交代码：AplusB.py ，其代码内容和 data 目录下一致，最终测评显示，时间超时。

不知道是我哪里搞错了。

**Comment by alphagocc** [comment]
`AplusB.py`应该放在`source`下面？

**Comment by hemulab** [comment]
> `AplusB.py`应该放在`source`下面？

source目录下也有同样的测试AplusB.py文件。但是检测不成功，是不是print()不能检测？

**Comment by alphagocc** [comment]
文件输入输出？

**Comment by alphagocc** [comment]
没有后续回应，暂时关闭
