### ISSUE TITLE
[BUG] deb包中的 Qt 版本问题

### ISSUE THREAD

**Issue by accepted-zhs** [Project-LemonLime/Project_LemonLime#151]
**Describe the bug**
**描述一下这个 Bug**

Ubuntu 20.04 可以正常安装，但运行时提示Qt版本错误。

**To Reproduce**
**如何复现**

1. 安装最新 (0.3.1) Release中任意一个deb包
2. 在终端中运行lemon
3. 提示 `lemon: /lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.15' not found (required by lemon)
`

**Expected behavior**
**期望获得的结果**
应该可以正常运行

**Screenshots**
**有截图吗？**
![image](https://user-images.githubusercontent.com/57523005/147425160-ac0ec3c2-141b-4dd9-8c80-ab2db8a5526f.png)

**Environment:**
**环境：**
-   Version: 0.3.1
-   OS: Ubuntu 20.04.3

**Additional context**
**其他信息**
可能 Ubuntu 20.04 官方源默认是 Qt 5.12，而 lemon 需要 Qt 5.15 吧...

**Comment by alphagocc** [comment]
静态编译，请

**Comment by accepted-zhs** [comment]
> 静态编译，请

不太懂... 是最后这两个包吗？
```
LemonLime-linux-x86_64-Release
LemonLime-linux-x86_64-RelWithDebInfo 
```

并且四个deb包都试了，（不过 RelWithDebInfo 是什么意思...是带调试的意思吗）

**Comment by alphagocc** [comment]
> > 静态编译，请
> 
> 不太懂... 是最后这两个包吗？
> 
> ```
> LemonLime-linux-x86_64-Release
> LemonLime-linux-x86_64-RelWithDebInfo 
> ```
> 
> 并且四个deb包都试了，（不过 RelWithDebInfo 是什么意思...是带调试的意思吗）

是的，最后两个

**Comment by accepted-zhs** [comment]
感谢，不过静态编译的版本还存在图标缺失的问题。

（比如下图中“添加”按钮左侧原本应该是有“+”的图标）

![2022-01-01 13-27-28屏幕截图](https://user-images.githubusercontent.com/57523005/147844556-e7b3b2dd-9bb3-43fa-8f05-451dc9bf0c95.png)
