### ISSUE TITLE
[BUG] 关于页版本不正确

### ISSUE THREAD

**Issue by Henry-ZHR** [Project-LemonLime/Project_LemonLime#156]
**Describe the bug**

实际版本 `0.3.2.1`，关于页显示 `0.3.0-dev:201`

**To Reproduce**

1. 安装
2. 打开软件，点开“关于”

**Screenshots**

![图片](https://user-images.githubusercontent.com/51886614/151115301-07bafb11-4339-4eb8-ad71-42f18fec6f59.png)

**Environment:**

- Version: 0.3.2.1（AUR）
- OS: Arch Linux

**Additional context**

看起来是这俩文件没更新？

https://github.com/Project-LemonLime/Project_LemonLime/blob/master/makespec/VERSION  
https://github.com/Project-LemonLime/Project_LemonLime/blob/master/makespec/VERSIONSUFFIX

**Comment by alphagocc** [comment]
小问题，小问题.png
会修<del>(gugu)</del>的
