### ISSUE TITLE
[Feature] 考虑添加进 Homebrew cask 源里？

### ISSUE THREAD

**Issue by yzy-1** [Project-LemonLime/Project_LemonLime#163]
**Is your feature request related to a problem? Please describe.**
**你的功能请求是否与某些问题有关？请描述。**
如题，希望这个项目能添加进 Homebrew cask 源里，让 Mac 用户可以更方便地更新。

**Comment by alphagocc** [comment]
欢迎PR

**Comment by HeliumOI** [comment]
已经加入了

**Comment by CoelacanthusHex** [comment]
> 已经加入了

来个 pr 更新下 readme？
