### ISSUE TITLE
[BUG] spj 不支持绝对路径

### ISSUE THREAD

**Issue by 5ab-juruo** [Project-LemonLime/Project_LemonLime#166]
在使用 Special Judge/自定义校验器 功能时填入可执行文件，查阅文档，没有发现需要使用相对路径才可以。

然而在使用绝对路径时，评测会返回“校验器没有被正确配置”的结果，估计就是没有找到 checker。

## 复现
Windows 下，在比较模式-自定义校验器中填入绝对路径。

## 期待的效果
支持（Windows 风格的？）绝对路径。

## 环境
-   版本代号：0.3.3:217
-   OS: 系统：Windows 10.0.22000.739

**Comment by alphagocc** [comment]
期望的结果，考虑到跨设备，不会更改
