### ISSUE TITLE
[BUG]m1 macOS 增强测试点调整器分数输入问题

### ISSUE THREAD

**Issue by xiece666** [Project-LemonLime/Project_LemonLime#170]
在增强测试点调整器中，选中一个subtask后点“修改选中”，在得分一栏中backspace删除原来的分数，在删除最后的一个字符后分数变了回去。

**Expected behavior**
**期望获得的结果**
A clear and concise description of what you expected to happen. 清楚简明地描述你认为程序应该做的事情。
正常的被删为空

**Screenshots**
**有截图吗？**
If applicable, add screenshots to help explain your problem. 如果可以的话，附上屏幕截图来帮助表现 bug。

这是开始
![截屏2022-07-15 15 14 25](https://user-images.githubusercontent.com/92169702/179171827-2562cb4f-c688-42ac-a9df-5e3d75fca90b.png)

把0删掉
![截屏2022-07-15 15 15 09](https://user-images.githubusercontent.com/92169702/179171924-b0538689-7d2d-44af-9d24-0d25a219d78d.png)

把1删掉后自动补全为10
![截屏2022-07-15 15 15 56](https://user-images.githubusercontent.com/92169702/179172035-a41c5d56-d954-4c32-b3a3-b43d97b2970c.png)

**Environment:**
**环境：**
-   Version:  版本代号：0.3.3:218
-   OS: 系统：macOS 12.4 (m1)

**Comment by alphagocc** [comment]
期望的结果，因为不允许 0 分
