### ISSUE TITLE
在 Windows 10 上评测 Python 程序的限时问题

### ISSUE THREAD

**Issue by studyingegret** [Project-LemonLime/Project_LemonLime#171]
**描述一下这个 bug**

LemonLime 在 Windows 10 上评测 Python 程序时，限时有问题。

**如何复现**

1. 使用 LemonLime 自带的 Python 语言设置。
2. 打开一个新比赛。
3. 加入一个 A + B 题目：在 `data` 文件夹中创建文件夹 `aplusb`，里面添加 3 组测试数据（文件略…），在 LemonLime 中点击“控制>自动添加试题”，时间限制设为 1000 ms，空间限制设为 512 MB，点击“OK”。
4. 在 `source` 文件夹中加入以下选手：

   `testTLE1`:
   ```python
   for x in range(100000000):
       pass
   a, b = map(int, input().split())
   print(a + b)
   ```

   `testTLE2`:
   ```python
   while True:
       pass
   a, b = map(int, input().split())
   print(a + b)
   ```

   `testMLE`:
   ```python
   L = []
   for x in range(100000000):
       L.append("x" * 100000000)
   a, b = map(int, input().split())
   print(a + b)
   ```

   点击“选手”侧栏，点击“刷新”。
5. 点击“测试全部”。

**期望获得的结果**

对于每个测试点，`testTLE1` 运行 1 秒后被判 TLE，`testTLE2` 运行 1 秒后被判 TLE，`testMLE` 运行不到 1 秒后被判 MLE。

**实际结果**

对于每个测试点，`testTLE1` 运行约 4-6 秒后通过，`testTLE2` 运行约 8-10 秒后被判 TLE，`testMLE` 运行约 2 秒后被判 MLE。

**注：** 如果 `testTLE1` 的运行时间不足 1 秒，请增加循环次数。

<details>
   <summary><strong>环境</strong></summary>

LemonLime 版本：0.3.3:217\
编译信息：Build for Windows\
额外编译信息：Build on Windows x64\
构建日期：Mar 22 2022, 08:18:27\
CPython 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32\
OS：Windows 10
操作系统内部版本：19042.1526

</details>

**Comment by alphagocc** [comment]
Python 默认 10 倍时限，5 倍空间限制，可在编译器高级选项内更高

**Comment by studyingegret** [comment]
那这应该就是 UI 的问题了

在评测进度条上没有体现：

![屏幕截图 2022-07-31 223044](https://user-images.githubusercontent.com/110317665/182031480-f10f2791-9fb4-49a1-87ec-08d8602d2e6f.png)

在初次进入 LemonLime，设置编译器时也没有提示（这种对较慢语言放宽限制的机制我也是第一次看到）
