### ISSUE TITLE
关于macOS构建指南

### ISSUE THREAD

**Issue by tofucurd** [Project-LemonLime/Project_LemonLime#173]
``请使用 watcher_macos.cpp 编译 watcher_unix，否则内存限制会出问题。``

具体而言应该怎么做，还是说已经自动选择好了。

**Comment by alphagocc** [comment]
可以看看ci是怎么做的

**Comment by tofucurd** [comment]
请问一下什么是``ci``?

**Comment by alphagocc** [comment]
啊，不知道 `ci` 是啥啊。
我记得好像是自动选择好了，暂时无视这句话吧

**Comment by tofucurd** [comment]
好，谢谢
