### ISSUE TITLE
当程序试图非法读取文件时，LemonLime将整体崩溃

### ISSUE THREAD

**Issue by Cyril-44** [Project-LemonLime/Project_LemonLime#175]
如题，希望能修复，毕竟人多了难免有这种情况，我总不能一个一个查吧……

**Comment by Cyril-44** [comment]
TM，这不加freopen也崩溃是吧

**Comment by Cyril-44** [comment]
有人把`freopen("*.out","w",stdout);`写成了`freopen("*.out","r",stdout);`
#### 这种也会崩溃！！！

**Comment by alphagocc** [comment]
按照模板填写哦

**Comment by Cyril-44** [comment]
可是
