### ISSUE TITLE
当程序的freopen非法时，LemonLime将整体崩溃

### ISSUE THREAD

**Issue by Cyril-44** [Project-LemonLime/Project_LemonLime#176]
+ **描述一下这个 Bug**

如题，当有同学写成`freopen("*.out","r",stdout)`或不加`freopen`时，LemonLime会崩溃

+ **如何复现**

### 重现 Bug 的步骤：
1. 新建magic题目（文件读写）
2. 新建cpp文件并在在程序里写：
```cpp
#include <stdio.h>
int main() {
  freopen("magic.in", "r", stdin);
  freopen("magic.out", "r", stdout);
  return 0;
}
```
或者
```cpp
int main() {
  return 0;
}
```
3. 复制到source/example文件夹
4. 测试全部
5. 崩溃啦~

+ **期望获得的结果**

`FileIO Error` 文件读写错误 / `Runtime Error` 运行时错误

+ **环境：**

版本代号: 0.3.4:223
系统: Windows 11 22H2 (内部版本 22621.382)

+ ##### **其他信息**
###### 虽然那些学生讲了多少遍都不听，但是我总不能一个一个查吧。。。

**Comment by alphagocc** [comment]
无法复现

**Comment by Cyril-44** [comment]
???

**Comment by Cyril-44** [comment]
怎么会呢

**Comment by Cyril-44** [comment]
要不我录个视频吧

**Comment by Cyril-44** [comment]
https://user-images.githubusercontent.com/60605064/189490875-c3607005-44c8-4feb-95fb-88f19474f3ef.mp4

**Comment by alphagocc** [comment]
https://github.com/Project-LemonLime/Project_LemonLime/commit/9d9b221ea766282c0118942e8119a8abc477b6b0

**Comment by prayerhgq** [comment]
0.3.3没有这个问题，0.3.4确实有这个问题。

**Comment by alphagocc** [comment]
https://github.com/Project-LemonLime/Project_LemonLime/releases/tag/0.3.4.2

fixed
