### ISSUE TITLE
win10下文件操作如果写错会闪退

### ISSUE THREAD

**Issue by prayerhgq** [Project-LemonLime/Project_LemonLime#177]
例如： 写成：freopen("test","r",stdin);  没有写test.in，   lemon评测机就会闪退。

**Comment by alphagocc** [comment]
https://github.com/Project-LemonLime/Project_LemonLime/issues/176

**Comment by prayerhgq** [comment]
0.3.3没有这个问题，0.3.4确实有这个问题。
