### ISSUE TITLE
[BUG]对某道题切换编译器无效

### ISSUE THREAD

**Issue by tofucurd** [Project-LemonLime/Project_LemonLime#178]
**Describe the bug**
**描述一下这个 Bug**
无法对某道题切换编译器

**To Reproduce**
**如何复现**

1. 如图，选择g++作为题目conveyer的编译器
<img width="727" alt="截屏2022-09-11 17 10 59" src="https://user-images.githubusercontent.com/108205653/189520004-42dc632b-bad6-4231-a165-b5cd31249923.png">

2. 在某份conveyer的代码中，使用__lg函数，依然CE，而手动使用homebrew g++@12则没有问题。

P.S. 如果在步骤1后切换到其他题的界面（比如bubble）
<img width="727" alt="截屏2022-09-11 17 26 00" src="https://user-images.githubusercontent.com/108205653/189520580-e58f312b-6ca9-4146-8883-2bc3f95643e8.png">

再切回conveyer，则编译器又变回clang++了
<img width="728" alt="截屏2022-09-11 17 27 11" src="https://user-images.githubusercontent.com/108205653/189520623-eaa60d43-be3f-4e84-baaf-7aeda99a45bc.png">

**Expected behavior**
**期望获得的结果**

使用g++作为conveyer的编译器。

**Environment:**
**环境：**
-   Version:
<img width="420" alt="截屏2022-09-11 17 32 35" src="https://user-images.githubusercontent.com/108205653/189520789-359a24dc-4819-474b-a6b8-c8227d26d77b.png">

macOS 12.5.1

**Additional context**
**其他信息**

目前临时的解决办法是在设置中将g++设在首位，就可以用g++但用不了clang++，测完ce后再换回去。至于为什么不一直用g++，因为macOS下说实话homebrew g++确实有一些bug，加上了万能头的clang++是目前我所知道的一个较好的办法。

**Comment by alphagocc** [comment]
?
