### ISSUE TITLE
[Feature] 关于 #169 #142 RE 问题的想法

### ISSUE THREAD

**Issue by accepted-zhs** [Project-LemonLime/Project_LemonLime#185]
**Is your feature request related to a problem? Please describe.**
**你的功能请求是否与某些问题有关？请描述。**

见 #169 #142。

**Describe the solution you'd like**
**描述您想要的解决方案**

`size` 可以获取二进制文件中数据段的大小。一般 Linux 自带 `size` 程序，Windows 用 GNU Binutils 也会有 `size` 程序，macOS 不清楚。

可不可以提前利用 `size` 的输出判断这个程序非动态分配的内存是否超限，避免一开始就报 RE？如果没有 `size` 程序，就不判断。

**Additional context**
**补充内容**

感觉改改 `watcher_unix.cpp` 就行...

**Comment by tofucurd** [comment]
> size 可以获取二进制文件中数据段的大小。一般 Linux 自带 size 程序，Windows 用 GNU Binutils 也会有 size 程序，macOS 不清楚。

补充一下，macOS下也自带size
