### ISSUE TITLE
[BUG]#183未解决

### ISSUE THREAD

**Issue by tofucurd** [Project-LemonLime/Project_LemonLime#186]
#183 未解决，望重新打开

详见 #183

**Comment by tofucurd** [comment]
<img width="668" alt="截屏2022-09-14 14 45 05" src="https://user-images.githubusercontent.com/108205653/190080500-7d2d47f1-509f-48c3-bf7c-424fb3413bcb.png">
还是不行？（是不是我的问题？）

系统：macOS 12.6 (M1)

**Comment by tofucurd** [comment]
<img width="545" alt="截屏2022-09-14 15 07 55" src="https://user-images.githubusercontent.com/108205653/190085049-41b53d37-7ceb-41ce-a5eb-4c05d0eff3b4.png">
我手动把judgingtheard.cpp改成这样还是不行，有可能是其他地方？

**Comment by tofucurd** [comment]
<img width="771" alt="截屏2022-09-14 15 15 00" src="https://user-images.githubusercontent.com/108205653/190086563-de383279-fb2e-4de5-94f2-5b7d7a3fa746.png">

实测是这个地方，好像不能用``watcher.setPermissions``？

**Comment by CoelacanthusHex** [comment]
请直接在原 issue 评论，不要重复发送 issue
