### ISSUE TITLE
SPJ Bug

### ISSUE THREAD

**Issue by lihaoyu1234** [Project-LemonLime/Project_LemonLime#187]
**Describe the bug**
**描述一下这个 Bug**
Testlib 更新之后好像是锅了，满分不对，而且 SPJ 输出信息也不对，换成原来的 Testlib 就没有问题。

**Screenshots**
**有截图吗？**
<img width="675" alt="5-1" src="https://user-images.githubusercontent.com/50037056/190845822-e671a8e9-a6e9-4ffd-807c-71aa4c517195.png">
<img width="534" alt="5-2" src="https://user-images.githubusercontent.com/50037056/190845828-1b62f79f-d06f-43b7-8709-6f7f853d257c.png">
<img width="377" alt="5-3" src="https://user-images.githubusercontent.com/50037056/190845831-6965accf-a088-4a01-b4d8-918e83e693fe.png">
<img width="675" alt="5-4" src="https://user-images.githubusercontent.com/50037056/190845839-f5c63853-90e0-4403-ac91-cc168bd9d081.png">

**Environment:**
**环境：**
-   版本代号：0.3.4.2（0.3.4:227）
-   系统：Windows 11 22000.978
-   编译器：TDM-GCC 10.3
-   新版 SPJ：`Project_LemonLime/tree/master/assets/Testlib-for-Lemons @ c5d3b4e`
-   原来的 SPJ：`Project_LemonLime/releases/0.3.4.2/Lemon-0.3.4.2-source-all.7z/assets/Testlib-for-Lemons`

**Additional context**
**其他信息**

比赛文件包：
[2.zip](https://github.com/Project-LemonLime/Project_LemonLime/files/9591206/2.zip)

**Comment by lihaoyu1234** [comment]
@GitPinkRabbit

**Comment by registerGen** [comment]
![image](https://user-images.githubusercontent.com/62944333/190850717-1f163fd3-f3e7-44b9-adfd-106d95babbc8.png)

`#include "testlib.h"`？不应该是 `testlib_for_lemons.h` 吗（

**Comment by GitPinkRabbit** [comment]
@lihaoyu1234 @CoelacanthusHex 已于 GitPinkRabbit/Testlib-for-Lemons@058848b 修复

**Comment by GitPinkRabbit** [comment]
请求更新 submodule commit

**Comment by GitPinkRabbit** [comment]
可以关闭这个 issue 了
