### ISSUE TITLE
[BUG] 使用标准程序一直报答案错误

### ISSUE THREAD

**Issue by MasterYuan418** [Project-LemonLime/Project_LemonLime#188]
**Describe the bug**
**描述一下这个 Bug**
![图片](https://user-images.githubusercontent.com/58651976/193436173-395b65dc-2d1d-49c3-b330-a1c7f9107e7c.png)
如图所示，使用标准程序始终返回`6356720`。

**To Reproduce**
**如何复现**
1.  创建测试点
2.  选手提交程序
3.  点击`选手`-`测试全部`
4.  发生错误

**Expected behavior**
**期望获得的结果**
通过测试点

**Screenshots**
**有截图吗？**
![图片](https://user-images.githubusercontent.com/58651976/193436213-75eb6ed9-975a-4e1e-b563-5fe2557140d3.png)

![图片](https://user-images.githubusercontent.com/58651976/193436217-76f34b77-bfbc-40f9-8b72-78da60f2f4e5.png)

**Environment:**
**环境：**
-   Version: 0.3.4:227
-   OS: 
-   \[x] Windows (10 build 19043;x64)
-   \[ \] macOS
-   \[ \] Linux

**Comment by MasterYuan418** [comment]
补充：同样的测试点，同样的in out文件，第一题就会报错。
![图片](https://user-images.githubusercontent.com/58651976/193436589-d52b34d2-8c26-4345-9222-aa9f034d2616.png)

**Comment by alphagocc** [comment]
我怎么看不懂你在说什么，可以尝试重新表述一下吗

**Comment by MasterYuan418** [comment]
@alphagocc 我创建一题目后，使用标准程序（100%AC）的程序测试，发现测试点永远无法通过

**Comment by alphagocc** [comment]
怀疑是你写错了，可以找到一个最小的可复现的案例吗？

**Comment by MasterYuan418** [comment]
@alphagocc 从家庭版win10切换到专业版win10后该问题莫名其妙解决了，非常感谢你的协助。
