### ISSUE TITLE
请求改善mac的dmg美观度

### ISSUE THREAD

**Issue by hkr04** [Project-LemonLime/Project_LemonLime#19]
dmg里只放程序的话怪怪的，有点提示性的图片或文字比较好

![屏幕快照 2020-03-01 上午1 52 58](https://user-images.githubusercontent.com/54173798/75612590-f80f6280-5b5f-11ea-9e4b-d19dcd20674b.png)

[LemonLime_for_macOS.dmg.zip](https://github.com/iotang/Project_LemonLime/files/4270666/LemonLime_for_macOS.dmg.zip)

**Comment by ayalhw** [comment]
看来唐姐又要改Action了

**Comment by iotang** [comment]
还有这种事情

**Comment by hkr04** [comment]
![background](https://user-images.githubusercontent.com/54173798/75667648-face9c80-5cb2-11ea-8a67-24cde15fccd9.png)
这是背景图

**Comment by iotang** [comment]
问题来了，该怎么在命令行下实现这个呢

**Comment by hkr04** [comment]
> 问题来了，该怎么在命令行下实现这个呢

挠头，这个我不会

**Comment by iotang** [comment]
> > 问题来了，该怎么在命令行下实现这个呢
> 
> 挠头，这个我不会。在mac上通过图形化界面操作挺简单的

关键是我这里没有任何 mac 设备，mac 打包都是让 Github 的 Bot 打的，它们可不支持 GUI

**Comment by ayalhw** [comment]
> > > 问题来了，该怎么在命令行下实现这个呢
> > 
> > 
> > 挠头，这个我不会。在mac上通过图形化界面操作挺简单的
> 
> 关键是我这里没有任何 mac 设备，mac 打包都是让 Github 的 Bot 打的，它们可不支持 GUI

或许可以在仓库里塞个图片，打包时直接cp过去然后tar？

**Comment by hkr04** [comment]
> > > > 问题来了，该怎么在命令行下实现这个呢
> > > 
> > > 
> > > 挠头，这个我不会。在mac上通过图形化界面操作挺简单的
> > 
> > 
> > 关键是我这里没有任何 mac 设备，mac 打包都是让 Github 的 Bot 打的，它们可不支持 GUI
> 
> 或许可以在仓库里塞个图片，打包时直接cp过去然后tar？

问题是这样怎么确认图标位置

**Comment by Oneton429** [comment]
> > > 问题来了，该怎么在命令行下实现这个呢
> > 
> > 
> > 挠头，这个我不会。在mac上通过图形化界面操作挺简单的
> 
> 关键是我这里没有任何 mac 设备，mac 打包都是让 Github 的 Bot 打的，它们可不支持 GUI

我感觉您可以装个黑苹果（虚拟机也行/kk

**Comment by ayalhw** [comment]
> 我感觉您可以装个黑苹果（虚拟机也行/kk

我看看能不能装一个搞下吧
