### ISSUE TITLE
[BUG] NOI Linux2.0 无法使用

### ISSUE THREAD

**Issue by xiezheyuan** [Project-LemonLime/Project_LemonLime#191]
NOI Linix 无法使用lemonlime，自己编译或是使用deb安装都不行。

（不是支持吗）

**Comment by alphagocc** [comment]
支持

**Comment by Out-Of-Rain** [comment]
> NOI Linix 无法使用lemonlime，自己编译或是使用deb安装都不行。
> 
> （不是支持吗）

遇到了类似的问题，自己编译的时候qt6下不下来，deb安装提示缺依赖（？）
解决了的话拜托分享一个解决方法，跪谢orz
