### ISSUE TITLE
编译时错误:g++.exe: error: : No such file or directory(疑似扩展名问题)[BUG]

### ISSUE THREAD

**Issue by ride-donkey** [Project-LemonLime/Project_LemonLime#192]
在测评时会全部ce,错误是g++.exe: error: "题目设定的源文件名称(无后缀)": No such file or directory
如果把源文件名删掉后缀就会提示未找到选手文件
大概是编译的时候没有补扩展名?(不应该吧)
系统Windows10 21h2 x64,lemonlime0.3.4.2,使用MinGW

**Comment by alphagocc** [comment]
不可复现
