### ISSUE TITLE
[Feature]支持测评结果以Excel表格或csv表形式导出

### ISSUE THREAD

**Issue by Out-Of-Rain** [Project-LemonLime/Project_LemonLime#196]
**Is your feature request related to a problem? Please describe.**
**你的功能请求是否与某些问题有关？请描述。**
结果导出相关

**Describe the solution you'd like**
**描述您想要的解决方案**
新增以Excel表格或csv表形式导出测评结果

**Comment by CoelacanthusHex** [comment]
在 Windows 上本项目业已支持 XLS 导出，在 Linux 和 macOS 上实现困难。

**Comment by Out-Of-Rain** [comment]
> 在 Windows 上本项目业已支持 XLS 导出，在 Linux 和 macOS 上实现困难。

方才发现，够用，谢谢！
