### ISSUE TITLE
关于交互题编译

### ISSUE THREAD

**Issue by wgsylcl** [Project-LemonLime/Project_LemonLime#199]
交互题在编译的时候,总显示"__grader.cpp"不存在
用的是最新版的LemonLime,请问是我的配置错了吗
建议专门在Wiki上提供有关特殊题型的配置说明
<img width="767" alt="屏幕截图 2023-01-20 212458" src="https://user-images.githubusercontent.com/116442984/213705464-0d5f23bb-3297-46b4-9722-f23bf69d6515.png">
<img width="350" alt="屏幕截图 2023-01-20 212514" src="https://user-images.githubusercontent.com/116442984/213705467-c4a7876e-5a27-416a-beaf-7c753b46b8ca.png">

**Comment by alphagocc** [comment]
使用相对路径指定文件

**Comment by wgsylcl** [comment]
> 使用相对路径指定文件

谢谢,可以测了
建议在用户手册里写详细点,以免出现路径问题
