### ISSUE TITLE
[BUG] 通过 shutdown -s -t 0 命令可以被关机

### ISSUE THREAD

**Issue by hjl2011** [Project-LemonLime/Project_LemonLime#200]
**Describe the bug**
**描述一下这个 Bug**
如题，在选手程序执行 `system("shutdown -s -t 0");` 时，评测机会被关机。

**To Reproduce**
**如何复现**
1. 新建比赛、题目、选手。
2. 选手代码文件夹中新建 C++ 文件：
```cpp
#include <windows.h>

int main() {
    system("shutdown -s -t 0");
    return 0;
}
```
3. 全部评测。
4. 评测机关机了。

**Expected behavior**
**期望获得的结果**
评测机不会被关机。

**Screenshots**
**有截图吗？**
If applicable, add screenshots to help explain your problem. 如果可以的话，附上屏幕截图来帮助表现 bug。

**Environment:**
**环境：**
-   Version: (e.g. 0.2.2) 版本代号：0.3.4:227
-   OS: 系统：
-   Windows (Windows11 22H2)

**Additional context**
**其他信息**
Add any other context about the problem here. 如果，你还有想说的话……

**Comment by Dust1404** [comment]
Duplicate #64
