### ISSUE TITLE
需要32位Win7的Release

### ISSUE THREAD

**Issue by Cyril-44** [Project-LemonLime/Project_LemonLime#201]
### 前言
> 在学校机房，电脑全是Win7 32位，因为人多需要新版`LemonLime`的多线程评测。

### 我需要的
一个编译好的适用于32位Win7系统（Qt5）的`LemonLime 0.3.4.2`

**补充内容**
@alphagocc 大佬编译就开个/machine X86帮个忙，谢谢！

**Comment by alphagocc** [comment]
win7已经在今年eol，不会提供。
而且32位系统能开几个线程啊（

**Comment by Cyril-44** [comment]
> win7已经在今年eol，不会提供。 而且32位系统能开几个线程啊（

我们电脑4核的，一个班六七十人，评测要30min搞死人不是吗（（（（

**Comment by Cyril-44** [comment]
学校也死活不更新配置，15年的电脑（/wul
