### ISSUE TITLE
如何在NOILinux2.0上安装使用呢，尝试了很久一直在Qt5上出问题

### ISSUE THREAD

**Issue by nxppm** [Project-LemonLime/Project_LemonLime#208]

**Comment by alphagocc** [comment]
出了啥问题啊

**Comment by nxppm** [comment]
> 

现在通过 `apt install .deb`  已经们安装了，但是安装出来虽然有图标，但是点击没法运行

**Comment by nxppm** [comment]
> > 
> 
> 现在通过 `apt install .deb` 已经们安装了，但是安装出来虽然有图标，但是点击没法运行

在vm虚拟机上还是物理机直接装的noilinux2.0都不行

**Comment by alphagocc** [comment]
用那个静态链接的

**Comment by nxppm** [comment]
> 用那个静态链接的

就是根据静态链接，然后到release里面下载的deb然后  apt install 安装的，下载的那个链接是`https://github.com/Project-LemonLime/Project_LemonLime/releases/download/0.3.4.2/LemonLime-0.3.4.2-debian-sid-Release.deb`

**Comment by alphagocc** [comment]
？？？？

**Comment by alphagocc** [comment]
deb 不是静态链接的，静态链接的那个没有后缀，是一个直接的可执行程序

**Comment by nxppm** [comment]
> deb 不是静态链接的，静态链接的那个没有后缀，是一个直接的可执行程序

`https://github.com/Project-LemonLime/Project_LemonLime/releases/download/0.3.4.2/LemonLime-linux-x86_64-Release`这个嘛？？？这个怎么运行呢

**Comment by alphagocc** [comment]
对，`chmod +x <文件名>` 然后直接运行

**Comment by nxppm** [comment]
> 对，`chmod +x <文件名>` 然后直接运行

还真可以了，我用`./`运行的，有没有办法可以固定在收藏栏呢

**Comment by alphagocc** [comment]
不清楚，你可以自己研究一下
