### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Komodo2006** [Project-LemonLime/Project_LemonLime#212]
**Describe the bug**
**描述一下这个 Bug**
build时出现错误，cmake表示3rd party single application文件夹下无cmakelists.txt

**To Reproduce**
**如何复现**
Steps to reproduce the behavior: 像下面这样写出重现 Bug 的步骤：
fedora下编译即可。

**Expected behavior**
**期望获得的结果**
正常build

**Screenshots**
**有截图吗？**
![image](https://github.com/Project-LemonLime/Project_LemonLime/assets/47469863/a5b84fc2-fa23-434e-9513-e78f0db91098)

**Environment:**
**环境：**
-   Version: (e.g. 0.2.2) 版本代号：（比如 0.2.2）
-   OS: 系统：
-   \[ \] Windows (Which version? 哪个版本啊？)
-   \[ \] macOS
-   \[ \] Linux (Which edition and version? 哪个发行版和版本？)
fedora workstation 38

**Additional context**
**其他信息**
Add any other context about the problem here. 如果，你还有想说的话……

**Comment by CoelacanthusHex** [comment]
请仔细阅读构建文档，你的 submodule 没有设置成功。
https://github.com/Project-LemonLime/Project_LemonLime/blob/master/BUILD.md
