### ISSUE TITLE
添加判断格式错误颜色

### ISSUE THREAD

**Issue by xdfx2017** [Project-LemonLime/Project_LemonLime#219]
添加判断格式错误颜色
如文件夹错误，代码无freopen等

**Comment by alphagocc** [comment]
很抱歉，做不到

**Comment by xdfx2017** [comment]
1.可以判断代码如果没有freopen，则格式错误
2.可以只查找程序文件夹，如lib的程序在xxx/lib/lib.cpp
希望有此功能

**Comment by alphagocc** [comment]
> 1.可以判断代码如果没有freopen，则格式错误

那万一写的 fopen 呢


> 2.可以只查找程序文件夹，如lib的程序在xxx/lib/lib.cpp 希望有此功能
 
这个实现过了，你点那个整理选手文件夹。。。
