### ISSUE TITLE
[BUG]每道题第一个点都会TLE

### ISSUE THREAD

**Issue by nxppm** [Project-LemonLime/Project_LemonLime#224]
**Describe the bug**
**描述一下这个 Bug**
配置好的题，每道题第一个点都会TLE，都是以前用过的标准配置。代码是AC代码，交换第一个点和第二个点，新的第一个点依然会超时。将第一个点时间放宽之后依然会T。

**To Reproduce**
**如何复现**
1. 正常配置题目，正常设置数据和选手文件
2. 开始测试，编译之后，第一个点等很久，然后就TLE，随后每道题剩下的点都正常。

**Expected behavior**
**期望获得的结果**
正常评测

**Screenshots**
**有截图吗？**
If applicable, add screenshots to help explain your problem. 如果可以的话，附上屏幕截图来帮助表现 bug。

**Environment:**
**环境：**
-   Version: 0.2.10:120
-   OS: 系统：win10 教育版 1809  [操作系统版本：17763.1]

**Additional context**
**其他信息**
Add any other context about the problem here. 如果，你还有想说的话……

**Comment by CoelacanthusHex** [comment]
考虑关闭你的杀毒软件后重新检查一下是否还有问题。

**Comment by nxppm** [comment]
> 考虑关闭你的杀毒软件后重新检查一下是否还有问题。

好的，已解决。win10、win11都可以了
