### ISSUE TITLE
[BUG] 数字被显示为错误的字符

### ISSUE THREAD

**Issue by wtcsky** [Project-LemonLime/Project_LemonLime#233]
**Describe the bug**
**描述一下这个 Bug**
软件中所有的数字都变成了其他的符号，汉字和字母和一些字符没有受到影响。界面没有影响，只有测试后的所有数字。
问题可能是因为Windows自动更新了

**Screenshots**
**有截图吗？**
![lemon_qoaIdK9yaO](https://github.com/user-attachments/assets/040aad93-eb29-4ebd-b86e-a285a2d5fe3d)

**Environment:**
**环境：**
Windows 11 家庭中文版
23H2
22631.4317

**Comment by CoelacanthusHex** [comment]
首先这不叫乱码……其次感觉像是字体问题
目测和这里有关
https://github.com/Project-LemonLime/Project_LemonLime/blob/bd75de79c10c07e1b7dd77de5e04135a6d47a942/src/forms/statisticsbrowser.ui#L23
但是我没有 Windows，所以 cc @alphagocc

**Comment by alphagocc** [comment]
在我电脑(22635.4367)上没有问题。

此外 〇 是 U+3007 〈 是 U+3008 以此类推 疑似某种映射错误？

不清楚

**Comment by wtcsky** [comment]
最后发现是因为当时因为搞copilot修改了语言导致出现的问题，当时的区域格式改成了香港，改回正常的就可以了。
![ApplicationFrameHost_vfXU2MVsia](https://github.com/user-attachments/assets/2738da30-5994-4a15-9430-c2604e5b501b)
