### ISSUE TITLE
[BUG] Lost Configuration after upgrade

### ISSUE THREAD

**Issue by Suansuan-Keai** [Project-LemonLime/Project_LemonLime#68]
**Is your feature request related to a problem? Please describe.**
**您的功能请求是否与某些问题有关？请描述。**
希望可以将用户配置文件信息,即设置中的选项保存至用户文件夹.

**Describe the solution you'd like**
**描述您想要的解决方案（没有也可）**
本小白在升级Lemon_Lime的版本时直接替换文件夹会丢失数据和比赛历史记录.

**Additional context**
**补充内容**

**Comment by ayalhw** [comment]
我在 https://github.com/Project-LemonLime/Project_LemonLime/commit/85c2cab6ddf9805eafdcc9ce71d3e4a34bf794f9 中更改了设置保存路径并且忘记提供迁移和提醒，这是我的错
I changed the setting save path in https://github.com/Project-LemonLime/Project_LemonLime/commit/85c2cab6ddf9805eafdcc9ce71d3e4a34bf794f9 and forgot to provide migration and reminder, this is my fault

**Comment by ayalhw** [comment]
下一步计划替换掉目前使用的 QSetting 设置组件（该组件在 Windows 上将设置存入注册表，并且可配置性等都较差）

**Comment by Suansuan-Keai** [comment]
> 下一步计划替换掉目前使用的 QSetting 设置组件（该组件在 Windows 上将设置存入注册表，并且可配置性等都较差）

所以未来是存在Win的Users文件夹里还是别处?

**Comment by ayalhw** [comment]
> 所以未来是存在Win的Users文件夹里还是别处?

还在考虑中，目前是考虑按同目录 config 文件夹，User文件夹（或许还会有其他路径加入）的顺序 fallback ，这样便于复制迁移
