### ISSUE TITLE
[BUG] debian的包貌似有点小问题

### ISSUE THREAD

**Issue by accepted-zhs** [Project-LemonLime/Project_LemonLime#73]
系统：Ubuntu  20.04.1 Lemonlime：0.2.4

如果你安装了这个包，然后系统更新一下，然后...

**你的Lemonlime没了！**

这是因为这个包名字是lemon，ubuntu官方的软件源正好也有一个包叫lemon（当然这两个lemon完全不同），而且其版本号为3.31，比lemonlime的包"更新”！

所以系统误以为它们是同个软件包，只是版本不同，更新时会自动把这个lemon换成官方的软件源里的“假”lemon。然后，你的lemonlime会消失！

Like This：
![](https://gitee.com/accepted_zhs/Image/raw/master/2020-10-13%2017-54-07%20%E5%88%9B%E5%BB%BA%E7%9A%84%E6%88%AA%E5%9B%BE.png)

望修复！

**Comment by ayalhw** [comment]
New Build @0.2.6 
Package name will be lemonlime
