### ISSUE TITLE
[BUG] 对 TLE 的判定似乎有一些偏差

### ISSUE THREAD

**Issue by AutumnKite** [Project-LemonLime/Project_LemonLime#84]
如题，LemonLime 对 TLE 的判定似乎有一些偏差。

复现：

用如下代码做测试：

```cpp
#include <bits/stdc++.h>

int n;

int main() {
	std::cin >> n;

	int ans = 1;
	for (int i = 1; i <= n; ++i) {
		ans = 1ll * ans * i % 998244353;
	}

	for (int i = 1; i <= 500000; ++i) {
		std::cout << ans << std::endl;
	}
}
```

调整 n 的大小使得该程序大概需要执行 1.5s（本机测试时取了 n=4e8）。

在 LemonLime 中开 2s 时限会得到 TLE，开 3s 时限会正常结束并且运行时间为 1.5s 左右。

若将 `std::endl` 换成 `"\n"`，或只输出一个数时，一切正常。

无论是否使用标准输入输出都会得到以上结果。

测试环境为 Windows 10，MinGW 4.9.2 64-bit。LemonLime 为 Release 中的 [lemon-win-x64.zip](https://github.com/Project-LemonLime/Project_LemonLime/releases/download/0.2.6/lemon-win-x64.zip)，版本为 0.2.6。配置为 C++11 O2。

**Comment by AutumnKite** [comment]
在 NOI Linux 下也有这个问题，但是要时限开得更紧才会出现。

**Comment by alphagocc** [comment]
std::endl 会刷新输出缓冲区，这个缓冲区在内核中，所以这个是算在内核时间里的，而显示时间是用户时间，不包括刷新缓冲区时间。
Lemon算TLE时是在程序外掐了一个秒表，而显示是靠用户时间算的。
所以这是一个显示问题而不是TLE判定问题。

**Comment by alphagocc** [comment]
现在问题就变成了，要不要将内核时间加入运行时间

**Comment by Dust1404** [comment]
很多 OJ 也有这个问题。
按照 NOI 笔试题库，应该是只算 user time，但是如果不掐 real time，会很容易被卡死。
可能的解决办法可以把 extraTime 设大一点。

**Comment by ayalhw** [comment]
也许可以考虑吧掐死程序的时间和TLE判定用的时间分离开来

**Comment by alphagocc** [comment]
主要是以最上面这份代码为样例的话，用户时间已经和内核时间一样多了

另外频繁刷新缓冲区也是一个并非聪明的行为，我个人认为是有必要让这种人TLE的

<del>或者干脆把Bug变成Feature（逃）<del/>

**Comment by ayalhw** [comment]
就工程实践上来说，一般用 realtime 评判性能
至于 OI……

**Comment by Dust1404** [comment]
或许可以参考官方测评工具是怎么处理这个问题的

**Comment by alphagocc** [comment]
![image](https://user-images.githubusercontent.com/28982331/97956582-fe876580-1de3-11eb-81db-45d629aebd07.png)
使用IDA反编译得到
Arbiter是使用用户时间来计算的，这和LemonLime现行时间显示方案相同

**Comment by Dust1404** [comment]
目前 lemon 中存在一个 extra time，real time 超过 time limit + extra time 会掐掉程序返回 TLE。不过 extra time 可能设置的有点小。
cms 中掐掉程序的 real time 限制是题目时间限制的 2 倍。
