### ISSUE TITLE
[BUG]测试时随机 WA

### ISSUE THREAD

**Issue by Dust1404** [Project-LemonLime/Project_LemonLime#86]
OS：windows10 x64 1909 (18363.1139)
通过 Release v0.2.7 下载 `lemon-win-x64.zip` 及 `lemon-win-x86.zip` 均有此情况。

测试时随机 WA，从 WA 的信息来看大致情形是输出文件比答案文件短（显示第 1 行少或者某一个数字被截断）。对 std 进行测试十余次，每次 WA 的点都不同，基本排除 std 及数据问题。数据特征为输入或输出量较大，文件 IO。

尝试重启软件、重启系统，无效。

经过多次测试后复现概率降低，但仍有出现。

（曾经维护 lemonplus 时有人向我说过有莫名 WA 的问题，当时的单题重测就是为了这个开发的，但当时未复现，不清楚是否是同一个问题。）

暂不清楚其余系统是否存在这个问题。

**Comment by ayalhw** [comment]
我在 Arch Linux 上测试时似乎未曾遇到此问题

**Comment by Dust1404** [comment]
我正在尝试定位问题。

**Comment by Dust1404** [comment]
目前的进度：

可能是由于退出程序时部分 buffer 中的输出没有写入文件导致。基于如下判断：

- 部分测试点会有 4KB 左右的输出，但不完整，和 buffer 的 size 差不多，可能由于过程中自动清空 buffer 导致。
- 在程序最后加入 `fflush(stdout)` 或 `fclose(stdout)` 后问题不再复现。

尝试更换评测编译器，未解决。

**Comment by ayalhw** [comment]
感觉应当是 OS special 的一个问题
OS 在程序退出后应当扫尾刷新缓冲区并输出
我猜这里 Windows 可能是暴力清空了缓存区

**Comment by ayalhw** [comment]
如果在 Linux/macOS 不能复现此问题，那么就基本可以判断是 Windows 的实现问题

**Comment by Dust1404** [comment]
我准备再做如下测试：

- 不通过 Windows API 调用程序是否会出现此问题。
- 非 Qt 环境下通过 Windows API 调用程序是否会出现此问题。
- 不同版本的 Windows 下是否会出现此问题。
- lemon，lemonplus 及 lemonlime 早版本是否会出现此问题。

**Comment by Dust1404** [comment]
目前的测试结果：

- 不通过 Windows API 调用程序是否会出现此问题？不会
- 非 Qt 环境下通过 Windows API 调用程序是否会出现此问题？会
- 不同版本的 Windows 下是否会出现此问题？目前仅本机 (Windows 10 1909 18363.1139) 出错，虚拟机内纯净系统的 1903(18362.30)，1909(18363.592)，2004(19041.264)均不会出现此问题
- lemon，lemonplus 及 lemonlime 早版本是否会出现此问题。会

基于以上结果目前定位可能是某一个 Windows 版本 Windows API 的问题。

等后续测试本机更新系统后如果没有复现问题大概就可以关闭 issue 了。（Windows API 的问题咱也解决不了）

**Comment by Dust1404** [comment]
解决了，看起来是北大网盘（爱数的 AnyShare）客户端的问题，卸载了就没问题了。

（偶然测试忘关 360 还阴差阳错找到问题了，下面我可能要去研究下这个网盘到底干了些啥）
