### ISSUE TITLE
[BUG]关于添加多组测试点失败

### ISSUE THREAD

**Issue by llleix** [Project-LemonLime/Project_LemonLime#98]
添加多组测试点失败（有时候会闪退）

![1.PNG](https://i.loli.net/2020/11/25/no4kGYxuC9dsSab.png)
![2.PNG](https://i.loli.net/2020/11/25/NgjqHyeIVcoimwE.png)
![3.PNG](https://i.loli.net/2020/11/25/tPu21vZdcWNVor9.png)

 - Version: [0.2.7]
 - [x] Windows 10 20H2 [Build 19042.630]
 - [x] Windows 10 1607 [Build 14393.0]

**Comment by ayalhw** [comment]
Maybe this
https://github.com/Project-LemonLime/Project_LemonLime/blob/master/src/addtestcaseswizard.cpp#L179

**Comment by alphagocc** [comment]
你第二个表达式没打勾 @llleix

**Comment by ayalhw** [comment]
> 你第二个表达式没打勾 @llleix

草，这也行……

**Comment by llleix** [comment]
> 你第二个表达式没打勾 @llleix

打钩代表subtask编号啊

**Comment by alphagocc** [comment]
> 打钩代表subtask编号啊
不是，这个钩表示这个是不是正则表达式

**Comment by llleix** [comment]
> > 打钩代表subtask编号啊
> 
> 不是，这个钩表示这个是不是正则表达式
> 
> 你说的subtask编号，请直接在路径里面改

<>才是正则表达式
我试了三个都打勾也不行

**Comment by alphagocc** [comment]
> > > 打钩代表subtask编号啊
> > 
> > 
> > 不是，这个钩表示这个是不是正则表达式
> > 你说的subtask编号，请直接在路径里面改
> 
> <>才是正则表达式
> 我试了三个都打勾也不行

![image](https://user-images.githubusercontent.com/28982331/100235328-3d35b900-2f67-11eb-9ca3-d4539d4f91b8.png)
![image](https://user-images.githubusercontent.com/28982331/100235355-4757b780-2f67-11eb-95cc-f74de162e84c.png)
![image](https://user-images.githubusercontent.com/28982331/100235405-58a0c400-2f67-11eb-9f5a-0389f2449f27.png)

我实践下来好像是可以的

**Comment by llleix** [comment]
> > > > 打钩代表subtask编号啊
> > > 
> > > 
> > > 不是，这个钩表示这个是不是正则表达式
> > > 你说的subtask编号，请直接在路径里面改
> > 
> > 
> > <>才是正则表达式
> > 我试了三个都打勾也不行
> 
> ![image](https://user-images.githubusercontent.com/28982331/100235328-3d35b900-2f67-11eb-9ca3-d4539d4f91b8.png)
> ![image](https://user-images.githubusercontent.com/28982331/100235355-4757b780-2f67-11eb-95cc-f74de162e84c.png)
> ![image](https://user-images.githubusercontent.com/28982331/100235405-58a0c400-2f67-11eb-9f5a-0389f2449f27.png)
> 
> 我实践下来好像是可以的

这个bug是0.2.7有的
而且你这样subtask也绑错了
